# Fichier : aurore-ia/netlify.toml

[build]
  # On crée le dossier 'public' vide pour que Netlify ne déclenche pas d'erreur.
  command = "mkdir public"
  publish = "public"

[functions]
  directory = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
