# Configuration Netlify FINALE et CORRECTE pour aurore-ia
[build]
  command = "mkdir public"
  publish = "public"

[functions]
  directory = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  
# La section la plus importante qui active la mémoire.
[[stores]]
  name = "aurore-memory"
