# Configuration finale pour le déploiement sur Netlify

[build]
  command = "mkdir public"
  publish = "public"

[functions]
  directory = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  
# Cette section est la plus importante.
# Elle active le service "Blobs" pour ce site.
[[stores]]
  name = "aurore-memory"
