# Configuration Netlify FINALE pour aurore-ia
[build]
  command = "mkdir public"
  publish = "public"

[functions]
  directory = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

# Active la mémoire "aurore-memory"
[[stores]]
  name = "aurore-memory"
