# Fichier : aurore-ia/netlify.toml

[build]
  command = "echo 'Aucun build nécessaire'"
  publish = "public" 

# Syntaxe correcte avec simples crochets
[functions]
  directory = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
