[build]
  # On ignore les builds inutiles pour économiser les minutes
  ignore = "git diff --quiet HEAD^ HEAD . ':(exclude)netlify/functions/'"

[functions]
  directory = "netlify/functions"

# On déclare explicitement notre "store" de blobs
[[blobs]]
  store = "processed_urls"
