# Configuration Netlify FINALE pour le projet aurore-ia

[build]
  command = "mkdir public"
  publish = "public"

[functions]
  directory = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  
# La section la plus importante du projet, qui active la mémoire.
[[stores]]
  name = "aurore-memory"
