# Fichier : aurore-ia/netlify.toml

[build]
  command = "mkdir public"
  publish = "public"

[functions]
  directory = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  
# La ligne la plus importante de toute l'infrastructure :
# Elle active le service de "mémoire" (Blobs) pour ce site.
[[stores]]
  name = "aurore-memory"
