name: Aurore - cron
on:
  schedule:
    - cron: "*/10 * * * *"   # toutes les 10 minutes
  workflow_dispatch: {}
permissions:
  contents: write
  pull-requests: write
jobs:
  run-aurore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # --- NOUVELLE ÉTAPE DE DÉBOGAGE ---
      - name: DEBUG - Afficher les variables d'environnement
        run: |
          echo "--- Liste de toutes les variables d'environnement disponibles ---"
          env | sort
          echo "--- Vérification spécifique de BLOBS_PROXY_URL ---"
          echo "La variable BLOBS_PROXY_URL est-elle définie ? (via env) -> ${{ env.BLOBS_PROXY_URL != '' }}"
          echo "La variable BLOBS_PROXY_URL est-elle définie ? (via vars) -> ${{ vars.BLOBS_PROXY_URL != '' }}"
          echo "Valeur de la variable : ${{ vars.BLOBS_PROXY_URL }}"
          echo "--- Fin du débogage ---"

      - name: Run Aurore
        env:
          NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_SITE_REPO: ${{ secrets.GH_SITE_REPO }}
          GH_AUTHOR_NAME: ${{ secrets.GH_AUTHOR_NAME }}
          GH_AUTHOR_EMAIL: ${{ secrets.GH_AUTHOR_EMAIL }}
          AURORE_BLOBS_TOKEN: ${{ secrets.AURORE_BLOBS_TOKEN }}
          BLOBS_PROXY_URL: ${{ vars.BLOBS_PROXY_URL }}
          MAX_ARTICLES_PER_RUN: "2"
        run: |
          python -m src.aurore
