name: Aurore - cron
on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch: {}
permissions:
  contents: write
  pull-requests: write
jobs:
  run-aurore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Aurore
        env:
          # --- SECRETS ---
          GNEWS_API_KEY: ${{ secrets.GNEWS_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          AURORE_BLOBS_TOKEN: ${{ secrets.AURORE_BLOBS_TOKEN }}
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }} # <-- LA LIGNE AJOUTÉE

          # --- VARIABLES ---
          BLOBS_PROXY_URL: ${{ vars.BLOBS_PROXY_URL }}
          GH_SITE_REPO: ${{ vars.GH_SITE_REPO }}
          GH_AUTHOR_NAME: ${{ vars.GH_AUTHOR_NAME }}
          GH_AUTHOR_EMAIL: ${{ vars.GH_AUTHOR_EMAIL }}
          MAX_ARTICLES_PER_RUN: "1"
        run: |
          python -m src.aurore
