name: Aurore Article Generation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config: [libre, tech]

    # On définit les secrets pour tout le job
    env:
      GNEWS_API_KEY: ${{ secrets.GNEWS_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      AURORE_BLOBS_TOKEN: ${{ secrets.AURORE_BLOBS_TOKEN }}
      BLOBS_PROXY_URL: ${{ secrets.BLOBS_PROXY_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      # --- NOUVELLE ÉTAPE DE DÉBOGAGE ---
      - name: Debug - Vérifier les secrets Netlify
        run: |
          echo "--- Début du Débogage des Secrets ---"
          if [ -z "$AURORE_BLOBS_TOKEN" ]; then
            echo "ERREUR: Le secret AURORE_BLOBS_TOKEN est VIDE ou non transmis."
          else
            echo "Secret AURORE_BLOBS_TOKEN est présent."
            echo "Longueur du token: ${#AURORE_BLOBS_TOKEN}"
          fi

          if [ -z "$BLOBS_PROXY_URL" ]; then
            echo "ERREUR: Le secret BLOBS_PROXY_URL est VIDE ou non transmis."
          else
            echo "Secret BLOBS_PROXY_URL est présent: $BLOBS_PROXY_URL"
          fi
          echo "--- Fin du Débogage des Secrets ---"

      - name: Run Aurore Bot for ${{ matrix.config }}
        run: python -m src.aurore --config ${{ matrix.config }}
