# Nom du workflow qui apparaîtra dans l'onglet "Actions" de GitHub
name: Aurore Cron

# Déclencheurs du workflow
on:
  # Permet de lancer manuellement le workflow depuis l'interface GitHub
  workflow_dispatch:
    inputs:
      config:
        description: 'Configuration à exécuter (ex: libre ou tech)'
        required: true
        type: string

  # Exécution programmée
  schedule:
    - cron: '0 * * * *' # Exécution toutes les heures

# Définition des jobs à exécuter
jobs:
  run-aurore:
    # Le type de machine sur laquelle le job va s'exécuter
    runs-on: ubuntu-latest

    # Permissions pour le GITHUB_TOKEN
    permissions:
      contents: write

    # Séquence des étapes à exécuter
    steps:
      # Étape 1 : Récupérer le code du dépôt aurore-ia
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 : Configurer l'environnement Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Étape 3 : Installer les dépendances du projet
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Étape 4 : Exécuter le script d'Aurore
      - name: Run Aurore IA
        env:
          A_GH_TOKEN: ${{ secrets.A_GH_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GNEWS_API_KEY: ${{ secrets.GNEWS_API_KEY }}
          NETLIFY_BLOBS_TOKEN: ${{ secrets.NETLIFY_BLOBS_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        run: |
          set -e # Force le job à échouer si une commande plante
          
          # Si le workflow a été lancé manuellement, on utilise la config fournie
          if
