name: DIAGNOSTIC - Afficher la structure des fichiers

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug - Afficher tous les fichiers du projet (récursivement)
        run: |
          echo "--- ARBORESCENCE COMPLÈTE DU PROJET ---"
          ls -R
          echo "-------------------------------------"
