name: Aurore Pipeline

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Configuration à exécuter (ex: libre ou tech)'
        required: true
        type: string
  schedule:
    - cron: '0 * * * *'  # chaque heure

concurrency:
  group: aurore-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Run Aurore
        env:
          GNEWS_API_KEY: ${{ secrets.GNEWS_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GH_TOKEN:       ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN:   ${{ secrets.GH_TOKEN }}  # fallback
          BLOBS_PROXY_URL:     ${{ vars.BLOBS_PROXY_URL }}
          AURORE_BLOBS_TOKEN:  ${{ secrets.AURORE_BLOBS_TOKEN }}
          TWITTER_ACCESS_TOKEN:        ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          TWITTER_API_KEY:             ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET_KEY:      ${{ secrets.TWITTER_API_SECRET_KEY }}
          TWITTER_BEARER_TOKEN:        ${{ secrets.TWITTER_BEARER_TOKEN }}
        run: |
          set -e
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            python -m src.aurore --config "${{ github.event.inputs.config }}"
          else
            python -m src.aurore --config libre
            python -m src.aurore --config tech
          fi
