name: Aurore - cron
on:
  schedule:
    - cron: "*/10 * * * *"   # toutes les 10 minutes
  workflow_dispatch: {}
permissions:
  contents: write
  pull-requests: write
jobs:
  run-aurore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ... (étapes précédentes)
      - name: DEBUG - Afficher les variables et empreintes
        run: |
          echo "--- Vérification des variables ---"
          echo "La variable BLOBS_PROXY_URL est-elle définie ? (via vars) -> ${{ vars.BLOBS_PROXY_URL != '' }}"
          echo "Valeur : ${{ vars.BLOBS_PROXY_URL }}"
          echo "--- Vérification de l'empreinte du token ---"
          echo -n "${{ secrets.AURORE_BLOBS_TOKEN }}" | sha256sum | awk '{print "[DEBUG GITHUB] Empreinte du token utilisé : " substr($1, 1, 10) "..."}'
          echo "--- Fin du débogage ---"

      - name: Run Aurore
      # ... (le reste du fichier)
        env:
          # --- Les SECRETS ---
          GNEWS_API_KEY: ${{ secrets.GNEWS_API_KEY }}      # <- LA LIGNE IMPORTANTE
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          AURORE_BLOBS_TOKEN: ${{ secrets.AURORE_BLOBS_TOKEN }}

          # --- Les VARIABLES ---
          BLOBS_PROXY_URL: ${{ vars.BLOBS_PROXY_URL }}
          GH_SITE_REPO: ${{ vars.GH_SITE_REPO }}
          GH_AUTHOR_NAME: ${{ vars.GH_AUTHOR_NAME }}
          GH_AUTHOR_EMAIL: ${{ vars.GH_AUTHOR_EMAIL }}
          MAX_ARTICLES_PER_RUN: "2"
        run: |
          python -m src.aurore
