name: Aurore Article Generation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config: [libre, tech]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      # --- NOUVELLE ÉTAPE DE DÉBOGAGE ---
      - name: Debug - Lister les fichiers templates
        run: |
          echo "--- Contenu du dossier src/templates/ ---"
          ls -l src/templates/
          echo "----------------------------------------"

      - name: Run Aurore Bot for ${{ matrix.config }}
        env:
          GNEWS_API_KEY: ${{ secrets.GNEWS_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          AURORE_BLOBS_TOKEN: ${{ secrets.AURORE_BLOBS_TOKEN }}
          BLOBS_PROXY_URL: ${{ secrets.BLOBS_PROXY_URL }}
        run: python -m src.aurore --config ${{ matrix.config }}
