name: Aurore Cron – Libre

on:
  workflow_dispatch:
  schedule:
    # 6x/jour, décalé d'1h par rapport à Tech (UTC)
    - cron: '0 3,7,11,15,19,23 * * *'

concurrency:
  group: aurore-libre
  cancel-in-progress: false

jobs:
  run-libre:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TARGET: libre
      MIN_CHARS: '280'
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} # optionnel
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - name: Run Aurore (libre)
        run: python -m aurore
