name: Aurore Cron – Libre

on:
  workflow_dispatch:
  schedule:
    # 7×/jour (UTC) — décalé de -1h vs Tech
    - cron: '0 0,4,8,12,16,20,22 * * *'

concurrency:
  group: aurore-global
  cancel-in-progress: false

jobs:
  run-libre:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Sanity check config.json
        run: |
          python - <<'PY'
          import json; json.load(open('config.json','r',encoding='utf-8'))
          print('config.json OK')
          PY

      - name: Run Aurore (Libre)
        env:
          # --- Sélection du site ---
          SITE: libre

          # --- GitHub (PAT) ---
          GH_TOKEN: ${{ secrets.A_GH_TOKEN }}
          A_GH_TOKEN: ${{ secrets.A_GH_TOKEN }}

          # --- News & IA ---
          GNEWS_API_KEY: ${{ secrets.GNEWS_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

          # --- Netlify (si utilisé par le script) ---
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_BLOBS_TOKEN: ${{ secrets.NETLIFY_BLOBS_TOKEN }}

          # --- Twitter (mapping -> noms attendus par le code) ---
          TWITTER_API_KEY:       ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET:    ${{ secrets.TWITTER_API_SECRET_KEY }}
          TWITTER_ACCESS_TOKEN:  ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: python -m aurore
