name: Aurore Cron – Libre

on:
  workflow_dispatch:
  schedule:
    # Toutes les 4h (UTC) aux heures suivantes
    - cron: '0 2,6,10,14,18,22 * * *'

# Un seul run à la fois pour tout le repo (Libre/Tech confondus)
concurrency:
  group: aurore-global
  cancel-in-progress: false

jobs:
  run-libre:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Run Aurore (Libre)
        env:
          GNEWS_API_KEY: ${{ secrets.GNEWS_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GH_TOKEN:       ${{ secrets.GH_TOKEN }}     # Remplace si ton PAT s’appelle autrement
          GITHUB_TOKEN:   ${{ secrets.GH_TOKEN }}     # Fallback pour le code
          BLOBS_PROXY_URL:     ${{ vars.BLOBS_PROXY_URL }}
          AURORE_BLOBS_TOKEN:  ${{ secrets.AURORE_BLOBS_TOKEN }}
          TWITTER_ACCESS_TOKEN:        ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          TWITTER_API_KEY:             ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET_KEY:      ${{ secrets.TWITTER_API_SECRET_KEY }}
          TWITTER_BEARER_TOKEN:        ${{ secrets.TWITTER_BEARER_TOKEN }}
        run: |
          set -e
          python -m src.aurore --config libre
