name: Aurore Cron – Tech

on:
  workflow_dispatch:
  schedule:
    # 7x/jour, décalé d’1h par rapport à Libre
    - cron: '0 1,5,9,13,17,21,23 * * *'

permissions:
  contents: write

concurrency:
  group: aurore-tech
  cancel-in-progress: false

jobs:
  run-tech:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Sanity check config.json
        run: |
          python - <<'PY'
          import json; json.load(open('config.json','r',encoding='utf-8'))
          print('config.json OK')
          PY

      - name: Run Aurore (Tech)
        env:
          PYTHONPATH: src
          TARGET: tech
          # 👉 On mappe ton PAT partout
          A_GH_TOKEN: ${{ secrets.A_GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.A_GH_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GNEWS_API_KEY: ${{ secrets.GNEWS_API_KEY }}
        run: python -m aurore
